name: Auto Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: go to WebHost
      run: cd src/ZKEACMS.WebHost
    - name: restore publish tool
      run: dotnet tool restore
    - name: publish
      run: dotnet tool run publish-zkeacms
